module.exports = {
    eventTypes: {
        GAME_START: "GAME_START",
        RCL_CHANGE: "RCL_CHANGE",
        GCL_CHANGE: "GCL_CHANGE",
        CREEP_DIED: "CREEP_DIED",
        HOSTILE_CREEP_APPEARED: "HOSTILE_CREEP_APPEARED",
    },

    taskTypes: {
        SPAWN_CREEP: "spawn_creep",
        CHECKER: "checker",
        EXPANSION: "expansion",
        LONG_RANGE_MINING: "long_range_mining",
        MINING_OPERATION: "mining_operation",
        TOWER_OPERATION: "tower_operation",
        SYNC_EXTENSIONS: "sync_extensions",
        SYNC_TOWERS: "sync_towers",
        SYNC_ROADS: "sync_roads",
        SYNC_FORTIFICATIONS: "sync_fortifications",
        UPGRADE_CONTROLLER: "upgrade_controller",
        FILL_ENERGY: "fill_energy",
        FILL_SPAWN: "fill_spawn",
        FILL_EXTENSION: "fill_extension",
        FILL_TOWER: "fill_tower",
        BUILD: "build",
        REPAIR: "repair",
        RENEW_UNIVERSAL: "renew_universal",
        RENEW_HAULER: "renew_hauler",
    },

    actionTypes: {
        SPAWN_CREEP: "spawn_creep",
        MINE: "mine",
        PICKUP_RESOURCE: "pickup_resource",
        TAKE_RESOURCE: "take_resource",
        BUILD: "build",
        REPAIR: "repair",
        SCOUT_ROOM: "scout_room",
        CLAIM_CONTROLLER: "claim_controller",
        GO_TO_TARGET: "go_to_target",
        RETIRE_CREEP: "retire_creep",
        TAXI: "taxi",
        TOWER_ATTACK: "tower_attack",
        TOWER_REPAIR: "tower_repair",
        TOWER_HEAL: "tower_heal",
        PLACE_CONSTRUCTION_SITE: "place_construction_site",
        TRANSFER_ENERGY: "transfer_energy",
        UPGRADE_CONTROLLER: "upgrade_controller",
        CHECK_UNIVERSALS: "check_universals",
        CHECK_UNIVERSAL_RENEW: "check_universal_renew",
        CHECK_FILL_ENERGY: "check_fill_energy",
        CHECK_FILL_SPAWN: "check_fill_spawn",
        CHECK_FILL_EXTENSION: "check_fill_extension",
        CHECK_FILL_TOWER: "check_fill_tower",
        CHECK_EXPANSION: "check_expansion",
        CHECK_LONG_RANGE_MINING: "check_long_range_mining",
        CHECK_UPGRADE_CONTROLLER: "check_upgrade_controller",
        MOVE_TO_RENEW: "move_to_renew",
        RECALCULATE_UNIVERSALS_COUNT: "recalculate_universals_count",
        RENEW_CREEP: "renew_creep",
        SCOUT_OUTPOST_ROOM: "scout_outpost_room",
        SYNC_MINING_OPERATIONS: "sync_mining_operations",
        SYNC_ROOM_BUILDER: "sync_room_builder",
        SYNC_TOWER_OPERATIONS: "sync_tower_operations",
    },

    roles: {
        UNIVERSAL: "universal",
        MINER: "miner",
        SCOUT: "scout",
        OUTPOST_SCOUT: "outpost_scout",
        CLAIMER: "claimer",
        COLONIZER: "colonizer",
        HAULER: "hauler",
    },

    eventScopes: {
        GLOBAL: "global",
        ROOM: "room",
    },
};
